// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
async test "read_all" {
  let dir = @fs.opendir("src/fs")
  defer dir.close()
  let list = dir
    .read_all()
    .filter_map(x => if x is "target" { None } else { Some(x) })
  list.sort()
  json_inspect(list, content=[
    "dir.c", "stub.c", "dir.mbt", "file.mbt", "moon.pkg", "README.md", "utils.mbt",
    "watch.mbt", "tmpdir.mbt", "dir_test.mbt", "eof_test.mbt", "README.mbt.md", "constants.mbt",
    "lock_test.mbt", "stat_test.mbt", "walk_test.mbt", "deprecated.mbt", "mkdir_test.mbt",
    "watch_kqueue.c", "watch_test.mbt", "watch_unix.mbt", "access_test.mbt", "create_test.mbt",
    "rename_test.mbt", "tmpdir_test.mbt", "watch_inotify.c", "watch_windows.c", "watch_kqueue.mbt",
    "read_all_test.mbt", "realpath_test.mbt", "unimplemented.mbt", "watch_inotify.mbt",
    "watch_windows.mbt", "pkg.generated.mbti", "text_file_test.mbt", "timestamp_test.mbt",
    "named_pipe_test.mbt", "random_access_test.mbt", "unimplemented_test.mbt",
  ])
}

///|
async test "as_dir" {
  let dir_file = @fs.open("src/fs", mode=ReadOnly)
  guard dir_file.kind() is Directory
  let dir = dir_file.as_dir()
  defer dir.close()
  let list = dir.read_all()..sort()
  json_inspect(list, content=[
    "dir.c", "stub.c", "dir.mbt", "file.mbt", "moon.pkg", "README.md", "utils.mbt",
    "watch.mbt", "tmpdir.mbt", "dir_test.mbt", "eof_test.mbt", "README.mbt.md", "constants.mbt",
    "lock_test.mbt", "stat_test.mbt", "walk_test.mbt", "deprecated.mbt", "mkdir_test.mbt",
    "watch_kqueue.c", "watch_test.mbt", "watch_unix.mbt", "access_test.mbt", "create_test.mbt",
    "rename_test.mbt", "tmpdir_test.mbt", "watch_inotify.c", "watch_windows.c", "watch_kqueue.mbt",
    "read_all_test.mbt", "realpath_test.mbt", "unimplemented.mbt", "watch_inotify.mbt",
    "watch_windows.mbt", "pkg.generated.mbti", "text_file_test.mbt", "timestamp_test.mbt",
    "named_pipe_test.mbt", "random_access_test.mbt", "unimplemented_test.mbt",
  ])
}

///|
test "readdir clear errno" {
  @event_loop.with_event_loop() <| () => {
    // do something to set a non-zero errno
    try @fs.open("/this/file/does/not/exist", mode=ReadOnly) catch {
      _ => ()
    } noraise {
      _ => ()
    }
    let dir = @fs.opendir("src/fs")
    defer dir.close()
    let list = dir.read_all()
    inspect(
      list.length(),
      content=(
        #|39
      ),
    )
  }
}
