// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
async test "send_request basic" {
  @async.with_task_group() <| root => {
    let (r, w) = @io.pipe()
    root.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let _ = sender.send_request(Get, "/", extra_headers={
        "Host": "x.y.org",
        "User-Agent": "MoonBit",
      })
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Host: x.y.org\r
        #|User-Agent: MoonBit\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send_request stream" {
  @async.with_task_group() <| root => {
    let (r, w) = @io.pipe()
    root.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let file = @fs.open("LICENSE", mode=ReadOnly)
      defer file.close()
      let _ = sender.send_request(Get, "/", extra_headers={
        "Host": "x.y.org",
        "User-Agent": "MoonBit",
      })
      sender..write_reader(file).end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Host: x.y.org\r
        #|User-Agent: MoonBit\r
        #|Accept-Encoding: gzip,identity\r
        #|Transfer-Encoding: chunked\r
        #|\r
        #|3f9\r
        #|
        #|                                 Apache License
        #|                           Version 2.0, January 2004
        #|                        http://www.apache.org/licenses/
        #|
        #|   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        #|
        #|   1. Definitions.
        #|
        #|      "License" shall mean the terms and conditions for use, reproduction,
        #|      and distribution as defined by Sections 1 through 9 of this document.
        #|
        #|      "Licensor" shall mean the copyright owner or entity authorized by
        #|      the copyright owner that is granting the License.
        #|
        #|      "Legal Entity" shall mean the union of the acting entity and all
        #|      other entities that control, are controlled by, or are under common
        #|      control with that entity. For the purposes of this definition,
        #|      "control" means (i) the power, direct or indirect, to cause the
        #|      direction or management of such entity, whether by contract or
        #|      otherwise, or (ii) ownership of fifty percent (50%) or more of the
        #|      outstanding shares, or (iii) beneficial ownership of such en\r
        #|3f9\r
        #|tity.
        #|
        #|      "You" (or "Your") shall mean an individual or Legal Entity
        #|      exercising permissions granted by this License.
        #|
        #|      "Source" form shall mean the preferred form for making modifications,
        #|      including but not limited to software source code, documentation
        #|      source, and configuration files.
        #|
        #|      "Object" form shall mean any form resulting from mechanical
        #|      transformation or translation of a Source form, including but
        #|      not limited to compiled object code, generated documentation,
        #|      and conversions to other media types.
        #|
        #|      "Work" shall mean the work of authorship, whether in Source or
        #|      Object form, made available under the License, as indicated by a
        #|      copyright notice that is included in or attached to the work
        #|      (an example is provided in the Appendix below).
        #|
        #|      "Derivative Works" shall mean any work, whether in Source or Object
        #|      form, that is based on (or derived from) the Work and for which the
        #|      editorial revisions, annotations, elabor\r
        #|3f9\r
        #|ations, or other modifications
        #|      represent, as a whole, an original work of authorship. For the purposes
        #|      of this License, Derivative Works shall not include works that remain
        #|      separable from, or merely link (or bind by name) to the interfaces of,
        #|      the Work and Derivative Works thereof.
        #|
        #|      "Contribution" shall mean any work of authorship, including
        #|      the original version of the Work and any modifications or additions
        #|      to that Work or Derivative Works thereof, that is intentionally
        #|      submitted to Licensor for inclusion in the Work by the copyright owner
        #|      or by an individual or Legal Entity authorized to submit on behalf of
        #|      the copyright owner. For the purposes of this definition, "submitted"
        #|      means any form of electronic, verbal, or written communication sent
        #|      to the Licensor or its representatives, including but not limited to
        #|      communication on electronic mailing lists, source code control systems,
        #|      and issue tracking systems that are m\r
        #|3f9\r
        #|anaged by, or on behalf of, the
        #|      Licensor for the purpose of discussing and improving the Work, but
        #|      excluding communication that is conspicuously marked or otherwise
        #|      designated in writing by the copyright owner as "Not a Contribution."
        #|
        #|      "Contributor" shall mean Licensor and any individual or Legal Entity
        #|      on behalf of whom a Contribution has been received by Licensor and
        #|      subsequently incorporated within the Work.
        #|
        #|   2. Grant of Copyright License. Subject to the terms and conditions of
        #|      this License, each Contributor hereby grants to You a perpetual,
        #|      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
        #|      copyright license to reproduce, prepare Derivative Works of,
        #|      publicly display, publicly perform, sublicense, and distribute the
        #|      Work and such Derivative Works in Source or Object form.
        #|
        #|   3. Grant of Patent License. Subject to the terms and conditions of
        #|      this License, each Contributor hereby grants to You a perpetual,
        #|      w\r
        #|3f9\r
        #|orldwide, non-exclusive, no-charge, royalty-free, irrevocable
        #|      (except as stated in this section) patent license to make, have made,
        #|      use, offer to sell, sell, import, and otherwise transfer the Work,
        #|      where such license applies only to those patent claims licensable
        #|      by such Contributor that are necessarily infringed by their
        #|      Contribution(s) alone or by combination of their Contribution(s)
        #|      with the Work to which such Contribution(s) was submitted. If You
        #|      institute patent litigation against any entity (including a
        #|      cross-claim or counterclaim in a lawsuit) alleging that the Work
        #|      or a Contribution incorporated within the Work constitutes direct
        #|      or contributory patent infringement, then any patent licenses
        #|      granted to You under this License for that Work shall terminate
        #|      as of the date such litigation is filed.
        #|
        #|   4. Redistribution. You may reproduce and distribute copies of the
        #|      Work or Derivative Works thereof in any medium, with or\r
        #|3f9\r
        #| without
        #|      modifications, and in Source or Object form, provided that You
        #|      meet the following conditions:
        #|
        #|      (a) You must give any other recipients of the Work or
        #|          Derivative Works a copy of this License; and
        #|
        #|      (b) You must cause any modified files to carry prominent notices
        #|          stating that You changed the files; and
        #|
        #|      (c) You must retain, in the Source form of any Derivative Works
        #|          that You distribute, all copyright, patent, trademark, and
        #|          attribution notices from the Source form of the Work,
        #|          excluding those notices that do not pertain to any part of
        #|          the Derivative Works; and
        #|
        #|      (d) If the Work includes a "NOTICE" text file as part of its
        #|          distribution, then any Derivative Works that You distribute must
        #|          include a readable copy of the attribution notices contained
        #|          within such NOTICE file, excluding those notices that do not
        #|          pertain to any part of the Derivative Works, in at least one\r
        #|3f9\r
        #|
        #|          of the following places: within a NOTICE text file distributed
        #|          as part of the Derivative Works; within the Source form or
        #|          documentation, if provided along with the Derivative Works; or,
        #|          within a display generated by the Derivative Works, if and
        #|          wherever such third-party notices normally appear. The contents
        #|          of the NOTICE file are for informational purposes only and
        #|          do not modify the License. You may add Your own attribution
        #|          notices within Derivative Works that You distribute, alongside
        #|          or as an addendum to the NOTICE text from the Work, provided
        #|          that such additional attribution notices cannot be construed
        #|          as modifying the License.
        #|
        #|      You may add Your own copyright statement to Your modifications and
        #|      may provide additional or different license terms and conditions
        #|      for use, reproduction, or distribution of Your modifications, or
        #|      for any such Derivative Works as a whole, pro\r
        #|3f9\r
        #|vided Your use,
        #|      reproduction, and distribution of the Work otherwise complies with
        #|      the conditions stated in this License.
        #|
        #|   5. Submission of Contributions. Unless You explicitly state otherwise,
        #|      any Contribution intentionally submitted for inclusion in the Work
        #|      by You to the Licensor shall be under the terms and conditions of
        #|      this License, without any additional terms or conditions.
        #|      Notwithstanding the above, nothing herein shall supersede or modify
        #|      the terms of any separate license agreement you may have executed
        #|      with Licensor regarding such Contributions.
        #|
        #|   6. Trademarks. This License does not grant permission to use the trade
        #|      names, trademarks, service marks, or product names of the Licensor,
        #|      except as required for reasonable and customary use in describing the
        #|      origin of the Work and reproducing the content of the NOTICE file.
        #|
        #|   7. Disclaimer of Warranty. Unless required by applicable law or
        #|      agreed to in writing, Licensor \r
        #|3f9\r
        #|provides the Work (and each
        #|      Contributor provides its Contributions) on an "AS IS" BASIS,
        #|      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
        #|      implied, including, without limitation, any warranties or conditions
        #|      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
        #|      PARTICULAR PURPOSE. You are solely responsible for determining the
        #|      appropriateness of using or redistributing the Work and assume any
        #|      risks associated with Your exercise of permissions under this License.
        #|
        #|   8. Limitation of Liability. In no event and under no legal theory,
        #|      whether in tort (including negligence), contract, or otherwise,
        #|      unless required by applicable law (such as deliberate and grossly
        #|      negligent acts) or agreed to in writing, shall any Contributor be
        #|      liable to You for damages, including any direct, indirect, special,
        #|      incidental, or consequential damages of any character arising as a
        #|      result of this License or out of the use or inab\r
        #|3f9\r
        #|ility to use the
        #|      Work (including but not limited to damages for loss of goodwill,
        #|      work stoppage, computer failure or malfunction, or any and all
        #|      other commercial damages or losses), even if such Contributor
        #|      has been advised of the possibility of such damages.
        #|
        #|   9. Accepting Warranty or Additional Liability. While redistributing
        #|      the Work or Derivative Works thereof, You may choose to offer,
        #|      and charge a fee for, acceptance of support, warranty, indemnity,
        #|      or other liability obligations and/or rights consistent with this
        #|      License. However, in accepting such obligations, You may act only
        #|      on Your own behalf and on Your sole responsibility, not on behalf
        #|      of any other Contributor, and only if You agree to indemnify,
        #|      defend, and hold each Contributor harmless for any liability
        #|      incurred by, or claims asserted against, such Contributor by reason
        #|      of your accepting any such warranty or additional liability.
        #|
        #|   END OF TERMS AND CONDITI\r
        #|3f9\r
        #|ONS
        #|
        #|   APPENDIX: How to apply the Apache License to your work.
        #|
        #|      To apply the Apache License to your work, attach the following
        #|      boilerplate notice, with the fields enclosed by brackets "[]"
        #|      replaced with your own identifying information. (Don't include
        #|      the brackets!)  The text should be enclosed in the appropriate
        #|      comment syntax for the file format. We also recommend that a
        #|      file or class name and description of purpose be included on the
        #|      same "printed page" as the copyright notice for easier
        #|      identification within third-party archives.
        #|
        #|   Copyright [yyyy] [name of copyright owner]
        #|
        #|   Licensed under the Apache License, Version 2.0 (the "License");
        #|   you may not use this file except in compliance with the License.
        #|   You may obtain a copy of the License at
        #|
        #|       http://www.apache.org/licenses/LICENSE-2.0
        #|
        #|   Unless required by applicable law or agreed to in writing, software
        #|   distributed under the License is distributed on an "AS IS" BASIS,
        #|   WITHOUT\r
        #|ab\r
        #| WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        #|   See the License for the specific language governing permissions and
        #|   limitations under the License.
        #|\r
        #|0\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send_request stream2" {
  @async.with_task_group() <| root => {
    let (r, w) = @io.pipe()
    root.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let _ = sender.send_request(Get, "/", extra_headers={
        "Host": "x.y.org",
        "User-Agent": "MoonBit",
      })
      sender.write("abcd")
      @async.sleep(50)
      sender.write("efgh")
      @async.sleep(50)
      sender.write("ijkl")
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Host: x.y.org\r
        #|User-Agent: MoonBit\r
        #|Accept-Encoding: gzip,identity\r
        #|Transfer-Encoding: chunked\r
        #|\r
        #|4\r
        #|abcd\r
        #|4\r
        #|efgh\r
        #|4\r
        #|ijkl\r
        #|0\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send invalid header" {
  @async.with_task_group() <| root => {
    let (r, w) = @io.pipe()
    root.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w, headers={ "Transfer-Encoding": "chunked" })
      let _ = sender.send_request(Get, "/", extra_headers={
        "Host": "x.y.org",
        "User-Agent": "MoonBit",
        "Transfer-Encoding": "chunked",
      })
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Host: x.y.org\r
        #|User-Agent: MoonBit\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send fixed length" {
  @async.with_task_group() <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let license_file = @fs.open("LICENSE", mode=ReadOnly)
      defer license_file.close()
      let header = "===== header =====\n"
      let trailer = "===== trailer =====\n"
      let total_size = license_file.size() +
        header.length().to_int64() +
        trailer.length().to_int64()
      let _ = sender.send_request(Get, "/", extra_headers={
        "Content-Length": total_size.to_string(),
      })
      sender
      ..write(header)
      ..write_reader(license_file)
      ..write(trailer)
      .end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Content-Length: 11397\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|===== header =====
        #|
        #|                                 Apache License
        #|                           Version 2.0, January 2004
        #|                        http://www.apache.org/licenses/
        #|
        #|   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        #|
        #|   1. Definitions.
        #|
        #|      "License" shall mean the terms and conditions for use, reproduction,
        #|      and distribution as defined by Sections 1 through 9 of this document.
        #|
        #|      "Licensor" shall mean the copyright owner or entity authorized by
        #|      the copyright owner that is granting the License.
        #|
        #|      "Legal Entity" shall mean the union of the acting entity and all
        #|      other entities that control, are controlled by, or are under common
        #|      control with that entity. For the purposes of this definition,
        #|      "control" means (i) the power, direct or indirect, to cause the
        #|      direction or management of such entity, whether by contract or
        #|      otherwise, or (ii) ownership of fifty percent (50%) or more of the
        #|      outstanding shares, or (iii) beneficial ownership of such entity.
        #|
        #|      "You" (or "Your") shall mean an individual or Legal Entity
        #|      exercising permissions granted by this License.
        #|
        #|      "Source" form shall mean the preferred form for making modifications,
        #|      including but not limited to software source code, documentation
        #|      source, and configuration files.
        #|
        #|      "Object" form shall mean any form resulting from mechanical
        #|      transformation or translation of a Source form, including but
        #|      not limited to compiled object code, generated documentation,
        #|      and conversions to other media types.
        #|
        #|      "Work" shall mean the work of authorship, whether in Source or
        #|      Object form, made available under the License, as indicated by a
        #|      copyright notice that is included in or attached to the work
        #|      (an example is provided in the Appendix below).
        #|
        #|      "Derivative Works" shall mean any work, whether in Source or Object
        #|      form, that is based on (or derived from) the Work and for which the
        #|      editorial revisions, annotations, elaborations, or other modifications
        #|      represent, as a whole, an original work of authorship. For the purposes
        #|      of this License, Derivative Works shall not include works that remain
        #|      separable from, or merely link (or bind by name) to the interfaces of,
        #|      the Work and Derivative Works thereof.
        #|
        #|      "Contribution" shall mean any work of authorship, including
        #|      the original version of the Work and any modifications or additions
        #|      to that Work or Derivative Works thereof, that is intentionally
        #|      submitted to Licensor for inclusion in the Work by the copyright owner
        #|      or by an individual or Legal Entity authorized to submit on behalf of
        #|      the copyright owner. For the purposes of this definition, "submitted"
        #|      means any form of electronic, verbal, or written communication sent
        #|      to the Licensor or its representatives, including but not limited to
        #|      communication on electronic mailing lists, source code control systems,
        #|      and issue tracking systems that are managed by, or on behalf of, the
        #|      Licensor for the purpose of discussing and improving the Work, but
        #|      excluding communication that is conspicuously marked or otherwise
        #|      designated in writing by the copyright owner as "Not a Contribution."
        #|
        #|      "Contributor" shall mean Licensor and any individual or Legal Entity
        #|      on behalf of whom a Contribution has been received by Licensor and
        #|      subsequently incorporated within the Work.
        #|
        #|   2. Grant of Copyright License. Subject to the terms and conditions of
        #|      this License, each Contributor hereby grants to You a perpetual,
        #|      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
        #|      copyright license to reproduce, prepare Derivative Works of,
        #|      publicly display, publicly perform, sublicense, and distribute the
        #|      Work and such Derivative Works in Source or Object form.
        #|
        #|   3. Grant of Patent License. Subject to the terms and conditions of
        #|      this License, each Contributor hereby grants to You a perpetual,
        #|      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
        #|      (except as stated in this section) patent license to make, have made,
        #|      use, offer to sell, sell, import, and otherwise transfer the Work,
        #|      where such license applies only to those patent claims licensable
        #|      by such Contributor that are necessarily infringed by their
        #|      Contribution(s) alone or by combination of their Contribution(s)
        #|      with the Work to which such Contribution(s) was submitted. If You
        #|      institute patent litigation against any entity (including a
        #|      cross-claim or counterclaim in a lawsuit) alleging that the Work
        #|      or a Contribution incorporated within the Work constitutes direct
        #|      or contributory patent infringement, then any patent licenses
        #|      granted to You under this License for that Work shall terminate
        #|      as of the date such litigation is filed.
        #|
        #|   4. Redistribution. You may reproduce and distribute copies of the
        #|      Work or Derivative Works thereof in any medium, with or without
        #|      modifications, and in Source or Object form, provided that You
        #|      meet the following conditions:
        #|
        #|      (a) You must give any other recipients of the Work or
        #|          Derivative Works a copy of this License; and
        #|
        #|      (b) You must cause any modified files to carry prominent notices
        #|          stating that You changed the files; and
        #|
        #|      (c) You must retain, in the Source form of any Derivative Works
        #|          that You distribute, all copyright, patent, trademark, and
        #|          attribution notices from the Source form of the Work,
        #|          excluding those notices that do not pertain to any part of
        #|          the Derivative Works; and
        #|
        #|      (d) If the Work includes a "NOTICE" text file as part of its
        #|          distribution, then any Derivative Works that You distribute must
        #|          include a readable copy of the attribution notices contained
        #|          within such NOTICE file, excluding those notices that do not
        #|          pertain to any part of the Derivative Works, in at least one
        #|          of the following places: within a NOTICE text file distributed
        #|          as part of the Derivative Works; within the Source form or
        #|          documentation, if provided along with the Derivative Works; or,
        #|          within a display generated by the Derivative Works, if and
        #|          wherever such third-party notices normally appear. The contents
        #|          of the NOTICE file are for informational purposes only and
        #|          do not modify the License. You may add Your own attribution
        #|          notices within Derivative Works that You distribute, alongside
        #|          or as an addendum to the NOTICE text from the Work, provided
        #|          that such additional attribution notices cannot be construed
        #|          as modifying the License.
        #|
        #|      You may add Your own copyright statement to Your modifications and
        #|      may provide additional or different license terms and conditions
        #|      for use, reproduction, or distribution of Your modifications, or
        #|      for any such Derivative Works as a whole, provided Your use,
        #|      reproduction, and distribution of the Work otherwise complies with
        #|      the conditions stated in this License.
        #|
        #|   5. Submission of Contributions. Unless You explicitly state otherwise,
        #|      any Contribution intentionally submitted for inclusion in the Work
        #|      by You to the Licensor shall be under the terms and conditions of
        #|      this License, without any additional terms or conditions.
        #|      Notwithstanding the above, nothing herein shall supersede or modify
        #|      the terms of any separate license agreement you may have executed
        #|      with Licensor regarding such Contributions.
        #|
        #|   6. Trademarks. This License does not grant permission to use the trade
        #|      names, trademarks, service marks, or product names of the Licensor,
        #|      except as required for reasonable and customary use in describing the
        #|      origin of the Work and reproducing the content of the NOTICE file.
        #|
        #|   7. Disclaimer of Warranty. Unless required by applicable law or
        #|      agreed to in writing, Licensor provides the Work (and each
        #|      Contributor provides its Contributions) on an "AS IS" BASIS,
        #|      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
        #|      implied, including, without limitation, any warranties or conditions
        #|      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
        #|      PARTICULAR PURPOSE. You are solely responsible for determining the
        #|      appropriateness of using or redistributing the Work and assume any
        #|      risks associated with Your exercise of permissions under this License.
        #|
        #|   8. Limitation of Liability. In no event and under no legal theory,
        #|      whether in tort (including negligence), contract, or otherwise,
        #|      unless required by applicable law (such as deliberate and grossly
        #|      negligent acts) or agreed to in writing, shall any Contributor be
        #|      liable to You for damages, including any direct, indirect, special,
        #|      incidental, or consequential damages of any character arising as a
        #|      result of this License or out of the use or inability to use the
        #|      Work (including but not limited to damages for loss of goodwill,
        #|      work stoppage, computer failure or malfunction, or any and all
        #|      other commercial damages or losses), even if such Contributor
        #|      has been advised of the possibility of such damages.
        #|
        #|   9. Accepting Warranty or Additional Liability. While redistributing
        #|      the Work or Derivative Works thereof, You may choose to offer,
        #|      and charge a fee for, acceptance of support, warranty, indemnity,
        #|      or other liability obligations and/or rights consistent with this
        #|      License. However, in accepting such obligations, You may act only
        #|      on Your own behalf and on Your sole responsibility, not on behalf
        #|      of any other Contributor, and only if You agree to indemnify,
        #|      defend, and hold each Contributor harmless for any liability
        #|      incurred by, or claims asserted against, such Contributor by reason
        #|      of your accepting any such warranty or additional liability.
        #|
        #|   END OF TERMS AND CONDITIONS
        #|
        #|   APPENDIX: How to apply the Apache License to your work.
        #|
        #|      To apply the Apache License to your work, attach the following
        #|      boilerplate notice, with the fields enclosed by brackets "[]"
        #|      replaced with your own identifying information. (Don't include
        #|      the brackets!)  The text should be enclosed in the appropriate
        #|      comment syntax for the file format. We also recommend that a
        #|      file or class name and description of purpose be included on the
        #|      same "printed page" as the copyright notice for easier
        #|      identification within third-party archives.
        #|
        #|   Copyright [yyyy] [name of copyright owner]
        #|
        #|   Licensed under the Apache License, Version 2.0 (the "License");
        #|   you may not use this file except in compliance with the License.
        #|   You may obtain a copy of the License at
        #|
        #|       http://www.apache.org/licenses/LICENSE-2.0
        #|
        #|   Unless required by applicable law or agreed to in writing, software
        #|   distributed under the License is distributed on an "AS IS" BASIS,
        #|   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        #|   See the License for the specific language governing permissions and
        #|   limitations under the License.
        #|===== trailer =====
        #|
      ),
    )
  }
}

///|
async test "sender write incorrect length" {
  @async.with_task_group() <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg(no_wait=true) <| () => {
      defer r.close()
      while r.read_some() is Some(_) {

      }
    }
    defer w.close()
    let sender = Sender::new(w)
    sender.send_response(200, "OK", cookies=[], request_method=Get, extra_headers={
      "Content-Length": "39",
    })
    let data = Bytes::make(20, b'\x00')
    sender.write(data)
    debug_inspect(
      @test_util.expect_error_async(() => sender.write(data)),
      content=(
        #|IncorrectBodyLength
      ),
    )
  }
}

///|
async test "sender write_reader incorrect length" {
  @async.with_task_group() <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg(no_wait=true) <| () => {
      defer r.close()
      while r.read_some() is Some(_) {

      }
    }
    defer w.close()
    let sender = Sender::new(w)
    let license_file = @fs.open("LICENSE", mode=ReadOnly)
    defer license_file.close()
    sender.send_response(200, "OK", cookies=[], request_method=Get, extra_headers={
      "Content-Length": "2048",
    })
    debug_inspect(
      @test_util.expect_error_async(() => sender.write_reader(license_file)),
      content=(
        #|IncorrectBodyLength
      ),
    )
  }
}

///|
async test "sender end_body incorrect length" {
  @async.with_task_group() <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg(no_wait=true) <| () => {
      defer r.close()
      while r.read_some() is Some(_) {

      }
    }
    defer w.close()
    let sender = Sender::new(w)
    sender.send_response(200, "OK", cookies=[], request_method=Get, extra_headers={
      "content-length": "1",
    })
    debug_inspect(
      @test_util.expect_error_async(() => sender.end_body()),
      content=(
        #|IncorrectBodyLength
      ),
    )
  }
}

///|
async test "send_response cookies" {
  let cookies = [
    Cookie("Cookie1", "value1"),
    Cookie(
      "Cookie2",
      "value2",
      path="/path/to/xxx",
      max_age=420000,
      secure=true,
    ),
    Cookie(
      "Cookie3",
      "value3",
      expires_raw="Sun, 06 Nov 1994 08:49:37 GMT",
      domain="example.moonbitlang.com",
      http_only=true,
    ),
    Cookie("Cookie4", "value four", extensions=["ExtNoArg", "ExtWithArg=xxx"]),
  ]
  @async.with_task_group() <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let _ = sender.send_response(200, "OK", cookies~, request_method=Get, extra_headers={})
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|HTTP/1.1 200 OK\r
        #|Set-Cookie: Cookie1=value1\r
        #|Set-Cookie: Cookie2=value2; Path=/path/to/xxx; Max-Age=420000; Secure\r
        #|Set-Cookie: Cookie3=value3; Expires=Sun, 06 Nov 1994 08:49:37 GMT; Domain=example.moonbitlang.com; HttpOnly\r
        #|Set-Cookie: Cookie4=value four; ExtNoArg; ExtWithArg=xxx\r
        #|Content-Length: 0\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send_request empty body" {
  @async.with_task_group <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let _ = sender.send_request(Get, "/", extra_headers={})
      sender..write("").end_body()
      let _ = sender.send_request(Head, "/", extra_headers={})
      sender.end_body()
      let _ = sender.send_request(Post, "/", extra_headers={})
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|HEAD / HTTP/1.1\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|POST / HTTP/1.1\r
        #|Accept-Encoding: gzip,identity\r
        #|Content-Length: 0\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "send_response empty body" {
  @async.with_task_group <| group => {
    let (r, w) = @io.pipe()
    group.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w)
      let _ = sender.send_response(200, "OK", cookies=[], request_method=Get, extra_headers={})
      sender.end_body()
      let _ = sender.send_response(200, "OK", cookies=[], request_method=Head, extra_headers={})
      sender..write("").end_body()
      let _ = sender.send_response(102, "OK", cookies=[], request_method=Get, extra_headers={})
      sender.end_body()
      let _ = sender.send_response(204, "OK", cookies=[], request_method=Get, extra_headers={})
      sender..write("").end_body()
      let _ = sender.send_response(304, "OK", cookies=[], request_method=Get, extra_headers={})
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|HTTP/1.1 200 OK\r
        #|Content-Length: 0\r
        #|\r
        #|HTTP/1.1 200 OK\r
        #|\r
        #|HTTP/1.1 102 OK\r
        #|\r
        #|HTTP/1.1 204 OK\r
        #|\r
        #|HTTP/1.1 304 OK\r
        #|\r
        #|
      ),
    )
  }
}

///|
async test "sender persistent header" {
  @async.with_task_group() <| root => {
    let (r, w) = @io.pipe()
    root.spawn_bg() <| () => {
      defer w.close()
      let sender = Sender::new(w, headers={
        "Host": "x.y.org",
        "User-Agent": "MoonBit",
      })
      let _ = sender.send_request(Get, "/", extra_headers={})
      sender.end_body()
    }
    defer r.close()
    inspect(
      r.read_all().binary() |> @bytes_util.ascii_to_string,
      content=(
        #|GET / HTTP/1.1\r
        #|Host: x.y.org\r
        #|User-Agent: MoonBit\r
        #|Accept-Encoding: gzip,identity\r
        #|\r
        #|
      ),
    )
  }
}
